name: input-output
on:
    push: 
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: print output1
              run: |
                echo "test1=hello" >> $GITHUB_OUTPUT
                echo $"{{GITHUB_OUTPUT}}"