name: input-output
on:
    workflow_dispatch:
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: print output1
              run: |
                echo "test1=hello" >> $GITHUB_OUTPUT
                echo $"{{GITHUB_OUTPUT}}"