name: input-output

on:
  workflow_dispatch: 

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.print1.outputs.test1 }}

    steps:
      - name: print output1
        id: print1
        run: |
          echo "test1=hello" >> $GITHUB_OUTPUT
          echo "the output value is: ${{ steps.print1.outputs.test1 }}"
