name: input-output
on: 
  workflow_dispatch: 
    
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: set output
        id: set
        run: echo "set=hello" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: use job1 output
        run: |
          echo "Job output is: ${{ needs.job1.outputs.set }}"
